## Basic Configuration

baseurl = "https://www.jakubpawelczak.com/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Jakub Pawelczak"
title = "Jakub Pawelczak"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
#enableRobotsTXT = true

## Site Settings
[params]
author = "Jakub M. Pawelczak"
intro = "I am an economist and PhD candidate at the University of Minnesota, and will be on the 2024/25 Economics Job Market"
description = "Email  <br/> pawel042@umn.edu"
authorimage = "me2.jpg"
dateformat = "2024"

## Custom CSS
customCSS = ["static/main.css"]  # Path to your custom CSS file in the static folder

## Site Meta Settings
[params.meta]
description = "Macroeconomist on the job market with research in Economics"
keywords = "macroeconomics, econ job market, research, job market candidate"

## Social Accounts
[params.social]
email = "pawel042@umn.edu"

## Extras
[params.extra]
copyright = "© 2024. Jakub Pawelczak. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = false
hightlightjs = false

## Main Menu
[[menu.main]]
    name = "Research"
    identifier = "Research"
    weight = 100
    url = "/research/"

[[menu.main]]
    name = "Teaching"
    weight = 200
    identifier = "Teaching"
    url = "/teaching/"

[[menu.main]]
    name = "About me"
    identifier = "About"
    weight = 300
    url = "/about/"
