## Basic Configuration

baseurl = "https://shenoybr.github.io/hugo-goa-demo/" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Jakub Pawelczak"
title = "Jakub Pawelczak"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
#googleAnalytics = "XYZ"
#enableRobotsTXT = true

## Site Settings
[params]
author = "Jakub M. Pawelczak"
intro = "PhD Candidate"
description = "University of Minnesota <br/> Department of Economics <br/> pawel042@umn.edu"
authorimage = "avatar.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
#github = "<username>"
#instagram = "<username>"
#linkedin = "<username>"
#twitter = "<username>"
#facebook = "<username>"
#google = "<username>"
#stackoverflow = "<username>"
email = "pawel042@umn.edu"

## Extras
[params.extra]
copyright = "© 2020. Jakub Pawelczak. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)." 
poweredby = false
hightlightjs = false

## Main Menu
[[menu.main]]
    name = "Research"
    identifier = "research"
    weight = 100
   url = "/research/"

[[menu.main]]
    name = "Teaching"
    weight = 200
    identifier = "blog"
    url = "/teaching/"
[[menu.main]]
    name = "about me"
    identifier = "about"
    weight = 300
    url = "/about/"





